[config]
CXX = "g++"
CXXFLAGS = [
    "-std=c++23",
    "-O2",
    "-Wall",
    "-I.",
    "-IDSU/**",
    "-IGraph/**",
    "-INumberTheory/**",
    "-IPolynomials/**",
    "-ISegmentTree/**",
    "-ISparseTable/**",
    "-IUtils/**"
]