name: Verify Code

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  set-run-matrix:
    runs-on: ubuntu-latest
    outputs:
      run-matrix: ${{ steps.set-run-matrix.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: make values
        id: set-run-matrix
        run: |
          list=$(find Tests/ -type f -name "*.test.cpp" -print0 | jq -R 'split("\u0000") | .[] | select(length > 0)' | jq -sc ".")
          echo "value=${list}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [ set-run-matrix ]
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        testcase: ${{fromJson(needs.set-run-matrix.outputs.run-matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make python3-pip
          pip3 install online-judge-verify-helper
      - name: Verify code
        timeout-minutes: 10
        run: oj-verify run ${{ matrix.testcase }}

  verify_check:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - run: echo "All tests passed!!"